spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

openai:
  model: gpt-3.5-turbo
  max-tokens: 1000
  temperature: 0.7
  timeout: 60
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_SECRET}
