spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baza_ai?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&connectTimeout=60000&socketTimeout=60000
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update  # This will recreate the database schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        connection:
          characterEncoding: utf8
          useUnicode: true
          CharSet: utf8

server:
  port: 8080

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo
